.eslintrc, .gitignore, .lintstagedrc, .prettierignore, .prettierrc, babel.config.js, package.json, tsconfig.json, yarn.lock
Adds project dependencies and development setup
=> Adds dependencies, sets up development files

server/models/interfaces.ts, server/services/IndexService.ts
Adds the backend IndexService that calls the Elasticsearch plugin. Some of the routes are temporary as those APIs are not implemented yet.
=> Adds backend IndexService

models/interfaces.ts, server/models/interfaces.ts, server/models/types.ts
=> Adds backend and common types

test/jest.config.js, test/mocks/historyMock.ts, test/mocks/httpClientMock.ts, test/mocks/index.ts, test/mocks/styleMock.ts, test/polyfills.ts, test/polyfills/mutationObserver.js, test/setup.jest.ts, test/setupTests.ts
=> Adds testing infrastructure

public/components/PolicyModal/PolicyModal.test.tsx, public/components/PolicyModal/PolicyModal.tsx, public/components/PolicyModal/index.ts
=> Adds policy modal component

public/components/ContentPanel/ContentPanel.test.tsx, public/components/ContentPanel/ContentPanel.tsx, public/components/ContentPanel/__snapshots__/ContentPanel.test.tsx.snap, public/components/ContentPanel/index.ts
Adds the ContentPanel component that will be used to structure sections of pages.
=> Adds ContentPanel component

public/pages/Indices/components/AddPolicyModal/AddPolicyModal.test.tsx, public/pages/Indices/components/AddPolicyModal/AddPolicyModal.tsx, public/pages/Indices/components/AddPolicyModal/__snapshots__/AddPolicyModal.test.tsx.snap, public/pages/Indices/components/AddPolicyModal/index.ts, public/pages/Indices/models/interfaces.ts, test/mocks/browserServicesMock.ts
=> Adds AddPolicyModal component

public/pages/Indices/components/IndexEmptyPrompt/IndexEmptyPrompt.test.tsx, public/pages/Indices/components/IndexEmptyPrompt/IndexEmptyPrompt.tsx, public/pages/Indices/components/IndexEmptyPrompt/__snapshots__/IndexEmptyPrompt.test.tsx.snap, public/pages/Indices/components/IndexEmptyPrompt/index.ts
Adds IndexEmptyPrompt component
=> Adds IndexEmptyPrompt component

public/pages/Indices/components/IndexControls/IndexControls.test.tsx, public/pages/Indices/components/IndexControls/IndexControls.tsx, public/pages/Indices/components/IndexControls/__snapshots__/IndexControls.test.tsx.snap, public/pages/Indices/components/IndexControls/index.ts
=> Adds IndexControls component

public/pages/Indices/components/IndexActions/IndexActions.test.tsx, public/pages/Indices/components/IndexActions/IndexActions.tsx, public/pages/Indices/components/IndexActions/__snapshots__/IndexActions.test.tsx.snap, public/pages/Indices/components/IndexActions/index.ts
=> Adds IndexActions component

server/services/PolicyService.ts, server/utils/helpers.ts
=> Adds PolicyService

server/models/interfaces.ts, server/services/IndexService.ts, server/services/ManagedIndexService.ts, server/services/index.ts, server/utils/helpers.ts
Adds ManagedIndexService, updates temporary addPolicy API
=> Adds ManagedIndexService, updates temporary addPolicy API

public/components/Modal/Modal.test.tsx, public/components/Modal/Modal.tsx, public/components/Modal/ModalRoot.tsx, public/components/Modal/index.ts
=> Adds ModalRoot and context

server/models/interfaces.ts, server/routes/index.ts, server/routes/indices.ts, server/routes/managedIndices.ts, server/routes/policies.ts, utils/constants.ts
=> Adds nodejs routes

public/pages/Policies/components/PolicyControls/PolicyControls.test.tsx, public/pages/Policies/components/PolicyControls/PolicyControls.tsx, public/pages/Policies/components/PolicyControls/__snapshots__/PolicyControls.test.tsx.snap, public/pages/Policies/components/PolicyControls/index.ts, public/pages/Policies/components/PolicyEmptyPrompt/PolicyEmptyPrompt.test.tsx, public/pages/Policies/components/PolicyEmptyPrompt/PolicyEmptyPrompt.tsx, public/pages/Policies/components/PolicyEmptyPrompt/__snapshots__/PolicyEmptyPrompt.test.tsx.snap, public/pages/Policies/components/PolicyEmptyPrompt/index.ts
=> Adds Policy page components

models/interfaces.ts, public/pages/Policies/containers/Policies/Policies.test.tsx, public/pages/Policies/containers/Policies/Policies.tsx, public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap, public/pages/Policies/containers/Policies/index.ts, public/pages/Policies/index.ts, public/pages/Policies/models/interfaces.ts, public/pages/Policies/utils/constants.ts, public/pages/Policies/utils/helpers.ts
Adds Policies, interfaces, consatants, helpers, tests
=> Adds Policies, interfaces, consatants, helpers, tests

public/pages/Indices/components/AddPolicyModal/AddPolicyModal.tsx, public/pages/Indices/components/IndexEmptyPrompt/IndexEmptyPrompt.test.tsx, public/pages/Indices/components/IndexEmptyPrompt/IndexEmptyPrompt.tsx, public/pages/Indices/containers/Indices/Indices.test.tsx, public/pages/Indices/containers/Indices/Indices.tsx, public/pages/Indices/models/interfaces.ts, public/pages/Indices/utils/constants.tsx, public/pages/Indices/utils/helpers.ts, public/services/IndexService.ts, server/services/IndexService.ts
…licy
Updates Indices components and tests and switches to actual add policy API
=> Updates Indices components and tests and switches to actual add policy API

public/pages/Policies/components/PolicyEmptyPrompt/PolicyEmptyPrompt.tsx, public/pages/Policies/containers/Policies/Policies.test.tsx, public/pages/Policies/containers/Policies/Policies.tsx, public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap
=> Cleans up policies and tests

public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.test.tsx
=> Updates CreatePolicy tests

public/components/ContentPanel/ContentPanelActions.tsx
Adds support for modal type actions in ContentPanelActions
=> Adds support for modal type actions in ContentPanelActions

public/app.js, public/components/DarkMode/DarkMode.tsx, public/components/DarkMode/index.ts, public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.tsx, public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
=> Adds dark mode support

public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap, public/pages/CreatePolicy/utils/constants.ts
Fixes incorrect mapping after update in backend index mappings
We changed mappings on index.
=> Fixes incorrect mapping after update in backend index mappings

public/components/ConfirmationModal/ConfirmationModal.test.tsx, public/components/ConfirmationModal/ConfirmationModal.tsx, public/components/ConfirmationModal/__snapshots__/ConfirmationModal.test.tsx.snap, public/components/ConfirmationModal/index.ts
Adds ConfirmationModal component to be used on actions like DeletePolicy, RemovePolicy
=> Adds ConfirmationModal component

public/pages/ChangePolicy/components/NewPolicy/NewPolicy.test.tsx, public/pages/ChangePolicy/components/NewPolicy/NewPolicy.tsx, public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap, public/pages/ChangePolicy/components/NewPolicy/index.ts, public/pages/ChangePolicy/models/interfaces.ts, public/pages/CreatePolicy/components/ConfigurePolicy/ConfigurePolicy.tsx
Adds NewPolicy component that will be used on the ChangePolicy page. It allows a user to select a new policy from combo box that they can search along with choosing whether to start the change from current place or a new state.
=> Adds NewPolicy component

public/pages/ChangePolicy/components/ChangeManagedIndices/ChangeManagedIndices.test.tsx, public/pages/ChangePolicy/components/ChangeManagedIndices/ChangeManagedIndices.tsx, public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap, public/pages/ChangePolicy/components/ChangeManagedIndices/index.ts
Adds ChangeManagedIndices component for changing a policy.
This lets you select your current managed indices and apply possible state filters to filter out indices.
=> Adds ChangeManagedIndices

public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.test.tsx, public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.tsx, public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap, public/pages/ChangePolicy/containers/ChangePolicy/index.ts, public/pages/ChangePolicy/index.ts, public/pages/Main/Main.tsx, public/utils/constants.ts
Adds ChangePolicy container page
This is missing more thorough tests which will be added in a later PR
=> Adds ChangePolicy container

server/routes/managedIndices.ts, server/services/ManagedIndexService.ts
Adds ChangePolicy API call/route on backend
=> Adds ChangePolicy API call/route on backend

public/pages/CreatePolicy/components/ConfigurePolicy/ConfigurePolicy.tsx, public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.test.tsx, public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.tsx, public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
Adds better error handling to creating policy
=> Adds better error handling to creating policy

public/components/PolicyModal/PolicyModal.tsx, public/components/PolicyModal/__snapshots__/PolicyModal.test.tsx.snap, public/pages/ManagedIndices/components/InfoModal/InfoModal.tsx, public/pages/ManagedIndices/components/InfoModal/__snapshots__/InfoModal.test.tsx.snap, public/pages/Policies/containers/Policies/Policies.test.tsx, public/pages/Policies/containers/Policies/Policies.tsx
Adds use of confirmation modal for deleting policies
Sets max width on modals because of huge JSON in policies
=> Adds use of confirmation modal for deleting policies

package.json, yarn.lock
=> Bump eslint-utils

package.json
=> Support Kibana 7.1.1 and Open Distro 1.1.0

public/pages/CreatePolicy/components/ConfigurePolicy/ConfigurePolicy.test.tsx, public/pages/Policies/containers/Policies/Policies.test.tsx
8c8590c3ca45:index-management-kibana-plugin dbbaughe$ yarn build
yarn run v1.15.2
$ plugin-helpers build
✨  Done in 37.62s.
8c8590c3ca45:index-management-kibana-plugin dbbaughe$ 
=> Fixes build issues from typescript

package.json
Updates plugin version for release
=> Updates plugin version

package.json
Adds support for Kibana 7.2.0
Test Suites: 27 passed, 27 total
Tests:       129 passed, 129 total
Snapshots:   24 passed, 24 total
Time:        25.604s
Ran all test suites.
✨  Done in 26.78s.
=> Adds support for Kibana 7.2.0

package.json
Adds support for Kibana 7.2.1
Test Suites: 27 passed, 27 total
Tests:       129 passed, 129 total
Snapshots:   24 passed, 24 total
Time:        30.901s
Ran all test suites.
✨  Done in 32.37s.
=> Adds support for Kibana 7.2.1

package.json, yarn.lock
Adds support for Kibana 7.3.2
Ran into issues with EuiIcon dynamic loading when using transitive Eui dependency from Kibana, so adding it as a hard dependency at last working version from Kibana 7.2.
Related issue: https://github.com/elastic/eui/issues/2530
=> Adds support for Kibana 7.3.2

opendistro-elasticsearch-index-management-kibana.release-notes.md
Adds release notes for first official supported version
=> Adds release notes for first official supported version

README.md, index.js, package.json, yarn.lock
* Add babel dependencies
* Adds regenerator-runtime and core-js dependencies for deprecated babel dep
* Updates README
=> Fixes broken build artifact (#69)

package.json
Bumping version for 1.3.0.1 release
=> Bump plugin version

opendistro-elasticsearch-index-management-kibana.release-notes.md
=> Updates release notes for 1.3.0.1

README.md, opendistro-elasticsearch-index-management-kibana.release-notes.md, package.json, public/components/ConfirmationModal/__snapshots__/ConfirmationModal.test.tsx.snap, public/components/PolicyModal/__snapshots__/PolicyModal.test.tsx.snap, public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap, public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap, public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap, public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap, public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap, public/pages/Indices/components/ApplyPolicyModal/__snapshots__/ApplyPolicyModal.test.tsx.snap, public/pages/Indices/components/IndexControls/__snapshots__/IndexControls.test.tsx.snap, public/pages/Indices/containers/Indices/Indices.test.tsx, public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap, public/pages/ManagedIndices/components/InfoModal/__snapshots__/InfoModal.test.tsx.snap, public/pages/ManagedIndices/components/ManagedIndexControls/__snapshots__/ManagedIndexControls.test.tsx.snap, public/pages/ManagedIndices/components/ManagedIndexEmptyPrompt/__snapshots__/ManagedIndexEmptyPrompt.test.tsx.snap, public/pages/ManagedIndices/components/RetryModal/__snapshots__/RetryModal.test.tsx.snap, public/pages/ManagedIndices/components/RolloverAliasModal/__snapshots__/RolloverAliasModal.test.tsx.snap, public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap, public/pages/Policies/components/PolicyControls/__snapshots__/PolicyControls.test.tsx.snap, public/pages/Policies/components/PolicyEmptyPrompt/__snapshots__/PolicyEmptyPrompt.test.tsx.snap, public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap, test/jest.config.js, test/setup.jest.ts, tsconfig.json, yarn.lock
Updates package.json kibana version.
New plugin structure is to have plugins in kibana/plugins instead of the sibling kibana-extra directory. Updates relative paths to reflect change.
Updates README with correct commands and steps.
Updates release notes.
EuiIcon dynamic imports in tests broke, added EuiIcon mock and updated relevant snapshots.
=> Adds support for Kibana 7.4.2

babel.config.js, index.js, package.json, public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx, yarn.lock
=> Backport update to 1.4 release branch

.github/workflows/unit-tests-workflow.yml
=> Adds basic unit test workflow

opendistro-elasticsearch-index-management-kibana.release-notes.md
=> Updates release notes

package.json, public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap, public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap, public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap, public/pages/Indices/components/ApplyPolicyModal/__snapshots__/ApplyPolicyModal.test.tsx.snap, public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap, public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap, public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap, public/utils/helpers.ts, release-notes/opendistro-elasticsearch-index-management-kibana-1.8.0.md, test/jest.config.js, yarn.lock
one path in `public/utils/helpers.ts` is changed, add a new mapping in `test/jest.config.js`
=> Adds support for Kibana 7.7.0

.github/workflows/release-workflow.yml
Adds release workflow that triggers when pushing tag
=> Adds release workflow

index.js, package.json, public/components/PolicyModal/__snapshots__/PolicyModal.test.tsx.snap, public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap, public/pages/ManagedIndices/components/InfoModal/__snapshots__/InfoModal.test.tsx.snap, public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap, public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap, release-notes/opendistro-elasticsearch-index-management-kibana-1.9.0.md
1. node version upgrade to 10.21.0 from 10.19.0 for kibana
2. move ISM under Management tab of Kibana Sidebar
=> add support for Kibana 7.8

package.json, yarn.lock
=> backport to branch 1.9: add brace dep for binary kibana not starting problem

index.js, public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx, public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap, public/pages/ManagedIndices/models/interfaces.ts, public/pages/ManagedIndices/utils/constants.ts, public/services/IndexService.ts, public/services/ManagedIndexService.ts, public/services/PolicyService.test.ts, public/services/PolicyService.ts, server/services/IndexService.ts, server/utils/helpers.ts
=> Opendistro 1.0

index.js
*[Issue](https://issues.amazon.com/issues/Kibana-1000)*
As per the requirement:
*Index management inserted in between DevTools and Stack Management in Kibana Side Menu*
=> changes for kibana side menu

package.json, release-notes/opendistro-for-elasticsearch-index-management-kibana-plugin.release-notes-1.11.0.0.md
=> Support OD version 1.11.0

.github/workflows/cypress-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, .github/workflows/unit-tests-workflow.yml, package.json, yarn.lock
*Issue #, if available: N/A*
- Update `cypress-io/github-action` to @v2.5.0. 
- Add `set-env` to braches that runs through workflow check.
=> Test cypress workflow set-env working

public/plugin.ts
Change position of index management plugin in side bar. 
The order is designed by UX designer and in step of 1000(https://github.com/elastic/kibana/blob/master/docs/development/core/public/kibana-plugin-core-public.appcategory.md). 
=> change position of index-management in kibana side bar

release-notes/opendistro-for-elasticsearch-index-management-kibana-plugin.release-notes-1.12.0.0.md
*Issue #, if available: N/A*
- Release note of the index management kibana for version 1.12.0.0
=> Release note for ODFE 1.12.0.0

release-notes/opendistro-for-elasticsearch-index-management-kibana-plugin.release-notes-1.12.0.0.md
*Issue #, if available: N/A*
Updating release note for 1.12.0.0
=> Update release note

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/cypress-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, .github/workflows/release-workflow.yml, .github/workflows/unit-tests-workflow.yml, CONTRIBUTING.md, README.md, test/polyfills/mutationObserver.js
- Replace all reference of "master' branch to "main" , here is the search result to [usage of "master" in repository](https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin/search?q=master)
- Add the Linux Foundation's Developer Certificate of Origin to pull request template
=> Rename "master" branch to "main" and add the Linux Foundation's Developer Certificate of Origin to pull request template

public/pages/Rollups/containers/Rollups/Rollups.tsx
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree …
=> Show enabled and continuous right on Rollup page

public/pages/Indices/utils/constants.tsx, public/pages/Rollups/containers/Rollups/__snapshots__/Rollups.test.tsx.snap
* Add a Copy to Clipboard button for copying index name
* Add updated snapshot
#164 
Added  a button for copying index name in one click.
**Updated Screenshot**
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; …
=> Add copyClipboard button beside index name (#164)
